### ISSUE TITLE
Standalone mode always False

### ISSUE THREAD

**Issue by AdrienPensart** [ewels/rich-click#20]
Hello,

it seems that `standalone_mode` is not propagated in:

https://github.com/ewels/rich-click/blob/8378cddfab5087a0d7e8f21433212c3cf0ac6b00/src/rich_click/rich_click.py#L525

Is this normal?

Because I often have:

```python 
int(main_cli.main(prog_name=PROG_NAME, **kwargs))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by ewels** [comment]
Yup, that's intentional. I set that to always be False so that Click always raises exceptions instead of catching and printing the error message (and exiting). I then catch the exceptions myself in the code just after the line you mentioned and either print or raise, according to the original value provided by the user:

https://github.com/ewels/rich-click/blob/8378cddfab5087a0d7e8f21433212c3cf0ac6b00/src/rich_click/rich_click.py#L527-L530

Your second code snippet doesn't make complete sense to me. Why are you calling the main click function within an `int()` call?

**Comment by AdrienPensart** [comment]
Nevermind, this was some legacy code, I'll correct it thank you!
