### ISSUE TITLE
`rich_click.rich_click` does not show up in auto-complete in VSCode

### ISSUE THREAD

**Issue by taranlu-houzz** [ewels/rich-click#52]
Not sure if this is an issue with my own VSCode setup, but for some reason, I am not getting proper autocompletions for `rich_click` on lines after the import. As I type the `import` I do get the expected completions, but after that, when using the imported module, they don't show up.

![image](https://user-images.githubusercontent.com/52425255/161337835-a6b57b68-257d-46ea-80e7-85929fa06378.png)

![image](https://user-images.githubusercontent.com/52425255/161337920-ea15f047-5fcd-4090-8eff-561bba5a5162.png)

Because the completion for `rich_click.r` did not show `rich_click`, I was confused for a moment.

**Comment by taranlu-houzz** [comment]
I should add that the code all works properly (e.g. I am able to use `rich_click.rich_click.*` as expected).

**Comment by ewels** [comment]
Is this issue related to https://github.com/ewels/rich-click/issues/57 ?

**Comment by taranlu-houzz** [comment]
Hmm, I'm not sure.. I don't really see how the `*args/**kwargs` issue mentioned would be related, but maybe?

**Comment by ewels** [comment]
Right, sorry - skim reading a bit too quickly.

Ok going back over your issue I think that this is due to some confusion over what's happening, not helped by the double use of the name `rich_click`. The first screenshot shows available _imports_, the second shows available _imported attributes_.

So, in your second screenshot, you have imported `rich_click` but not `rich_click.rich_click`. This submodule is not imported by the main package, which is why it isn't suggesting stuff under it - those things are not yet available. The suggestions show the methods available in the top-level `rich_click`, not available submodule imports.

If I import `rich_click.rich_click` instead of just `rich_click` then the autosuggestions work fine:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/465550/165626242-1ec183c0-f57c-4706-b222-b63470d60956.png">

<img width="647" alt="image" src="https://user-images.githubusercontent.com/465550/165626269-9c8f09ff-363a-4c68-80e5-8afd4c5eaa91.png">

Does this make sense? Apologies for the confusing naming. I did it this way because most people will be doing `import rich_click as click`. Then accessing `click.rich_click` makes sense..

**Comment by taranlu-houzz** [comment]
@ewels Ah, haha, my bad. In hindsight, that makes sense. Thanks for pointing that out!

**Comment by ewels** [comment]
No worries! Thanks for reporting, I suspect you won't be the only person coming across this..
